### ISSUE TITLE
customising colors

### ISSUE THREAD

**Issue by nigelwhite** [meditatingdragon/starter-gridsome-vuetify#1]
Thank you for a helpful starter.

I did git clone, npm install, gridsome build.

In src/main.js you say // adjust the theme if you would like to.....

I can't get this to work. When I change the hex values it makes no difference in the browser, even after a site rebuild. I guess it is working for you? Do you know what I may be missing?

Thanks
Nigel

**Comment by meditatingdragon** [comment]
It's because I used a specific color class to specify the header and footer elements. If you want to change the color based on the theme colors you create, just update the components to use 'primary' (or 'secondary') as the class, rather than 'teal darken-2'. Hope this helps.

**Comment by nigelwhite** [comment]
It is so helpful to see the way you've done that. The pattern of "colors.teal.darken2" is gonna be so useful. I see now it was my misunderstanding in the first place, but thanks for making it clearer.

Its also super interesting that the only dependency you've needed, to get the theme working, is webpack-node-externals. The setup doesn't need to be as complicated as I thought... (-:

Thanks again
